-- 코드를 입력하세요
SELECT USER_ID,NICKNAME, sum(PRICE) TOTAL_SALES
from USED_GOODS_BOARD
join USED_GOODS_USER 
on USED_GOODS_BOARD.WRITER_ID=USED_GOODS_USER.USER_ID
where STATUS="DONE"
group by WRITER_ID
having sum(PRICE)>=700000
order by TOTAL_SALES;