SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN 
(select max(PRICE) 
from FOOD_PRODUCT
GROUP BY CATEGORY)
and CATEGORY in ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;