-- 코드를 입력하세요
SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(SALES*PRICE) TOTAL_SALES
from BOOK b
join AUTHOR a
on b.AUTHOR_ID=a.AUTHOR_ID
join BOOK_SALES bs
on b.BOOK_ID=bs.BOOK_ID
where SALES_DATE like "2022-01%"
group by a.AUTHOR_ID, CATEGORY
order by a.AUTHOR_ID , CATEGORY desc